version: 2

models:
  - name: funnel
    tests:
      - dbt_datamocktool.unit_test:
          input_mapping:
            ref('orders'): ref('raw_orders_simple')
          expected_output: ref('dmt_expected__funnel_simple')
